{{- if .Values.imageCredentials.private }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flask-app.fullname" . }}-registry
  labels:
    app: {{ template "flask-app.name" . }}
    chart: {{ template "flask-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "flask-app.imagePullSecret" . }}
{{- end -}}
